# Generated by Django 6.0.4 on 2026-04-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='property_unlock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='realestate.propertyunlock'),
        ),
    ]
