# Generated by Django 6.0.4 on 2026-04-30 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery_latitude_and_more'),
        ('payments', '0003_initial'),
        ('realestate', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='property_unlock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='realestate.propertyunlock'),
        ),
    ]
