# Generated by Django 6.0.4 on 2026-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('order', 'Order Payment'), ('property_unlock', 'Property Unlock'), ('wallet_topup', 'Wallet Topup')], default='order', max_length=30),
        ),
    ]
