# Generated by Django 6.0.4 on 2026-05-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0001_initial'),
        ('payments', '0006_payment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitality.booking'),
        ),
    ]
