# Generated by Django 6.0.4 on 2026-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('order', 'Order Payment'), ('property_unlock', 'Property Unlock'), ('wallet_topup', 'Wallet Topup'), ('booking', 'booking')], default='order', max_length=30),
        ),
    ]
