# Generated by Django 6.0.4 on 2026-05-19 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('payments', '0008_alter_payment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.ticket'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('order', 'Order Payment'), ('property_unlock', 'Property Unlock'), ('wallet_topup', 'Wallet Topup'), ('booking', 'booking'), ('ticket', 'Event Ticket')], default='order', max_length=30),
        ),
    ]
