# Generated by Django 6.0.4 on 2026-05-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_ticket_purchase_alter_payment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('order', 'Order Payment'), ('property_unlock', 'Property Unlock'), ('wallet_topup', 'Wallet Topup'), ('booking', 'booking'), ('ticket', 'ticket')], default='order', max_length=30),
        ),
    ]
