# Generated by Django 5.2.5 on 2026-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_remove_escrowwallet_created_at_escrowwallet_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escrowwallet',
            old_name='seller',
            new_name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='escrowwallet',
            name='order',
        ),
        migrations.AddField(
            model_name='escrowwallet',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='escrowwallet',
            name='escrow_type',
            field=models.CharField(choices=[('order', 'Order'), ('booking', 'Booking'), ('ticket', 'Ticket'), ('property_unlock', 'Property Unlock')], default='order', max_length=30),
        ),
        migrations.AlterField(
            model_name='escrowwallet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
