# Generated by Django 5.2.5 on 2026-05-31 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_rename_seller_escrowwallet_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowwallet',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
