# Generated by Django 5.2.5 on 2026-05-31 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sellerorder'),
        ('payments', '0014_escrowwallet_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowwallet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='orders.order'),
        ),
    ]
