# Generated by Django 5.2.5 on 2026-05-31 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_escrowwallet_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowwallet',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
