# Generated by Django 5.2.5 on 2026-05-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_escrowwallet_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrowwallet',
            name='order',
        ),
    ]
