# Generated by Django 5.2.5 on 2026-08-23 07:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_escrowwallet_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_commission', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission % for marketplace product orders (e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('booking_commission', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission % for lodge & room bookings', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('property_unlock_commission', models.DecimalField(decimal_places=2, default=15.0, help_text='Commission % for real estate property contact unlocks', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('tickets_commission', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission % for event ticket sales', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Rate',
                'verbose_name_plural': 'Commission Rates',
            },
        ),
    ]
