# Generated by Django 5.2.5 on 2026-08-23 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_commissionrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionrate',
            options={'verbose_name': 'Global Commission Rate Settings', 'verbose_name_plural': 'Global Commission Rate Settings'},
        ),
        migrations.RemoveField(
            model_name='commissionrate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commissionrate',
            name='user',
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='booking_commission',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Global Commission % for lodge & room bookings', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='order_commission',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Global Commission % for marketplace product orders (e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='property_unlock_commission',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Global Commission % for real estate property contact unlocks', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionrate',
            name='tickets_commission',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Global Commission % for event ticket sales', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
