# Generated by Django 6.0.4 on 2026-05-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_phone_number',
            field=models.TextField(blank=True, max_length='100', null=True),
        ),
    ]
