# Generated by Django 6.0.4 on 2026-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
