# Generated by Django 6.0.4 on 2026-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_delivery_delivery_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='current_latitude',
            new_name='customer_latitude',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='current_longitude',
            new_name='customer_longitude',
        ),
        migrations.AddField(
            model_name='delivery',
            name='seller_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='seller_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
