# Generated by Django 6.0.4 on 2026-05-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_rename_current_latitude_delivery_customer_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='seller_latitude',
            new_name='pickup_latitude',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='seller_longitude',
            new_name='pickup_longitude',
        ),
    ]
