# Generated by Django 6.0.4 on 2026-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_rename_seller_latitude_delivery_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='user',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='full_name',
            field=models.CharField(default='reetr', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='id_number',
            field=models.CharField(default=3554656, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='phone_number',
            field=models.CharField(default=8787979, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('busy', 'Busy'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
