# Generated by Django 5.2.5 on 2026-05-31 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_sellerdelivery'),
        ('orders', '0006_order_delivery_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.DeleteModel(
            name='SellerDelivery',
        ),
    ]
