# Generated by Django 5.2.5 on 2026-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='escrow_released',
            field=models.BooleanField(default=False),
        ),
    ]
