# Generated by Django 5.2.5 on 2026-05-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_delivery_escrow_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='customer_delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
