# Generated by Django 6.0.4 on 2026-05-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Shop Owner'), ('property_owner', 'Property Owner'), ('hospitality_owner', 'Hospitality Owner'), ('event_organizer', 'Event Organizer'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
