# Generated by Django 6.0.4 on 2026-05-20 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_available_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='purchase_group',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
