# Generated by Django 5.2.5 on 2026-06-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ticketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='event',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
