# Generated by Django 5.2.5 on 2026-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
