# Generated by Django 5.2.5 on 2026-09-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_appevent_latitude_appevent_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
