# Generated by Django 6.0.4 on 2026-05-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunlock',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
