# Generated by Django 6.0.4 on 2026-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_propertyunlock_is_unlocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
