# Generated by Django 5.2.5 on 2026-07-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='shop_qr/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='qr_scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
