# Generated by Django 6.0.4 on 2026-05-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_companywallet_companywallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
