# Generated by Django 6.0.4 on 2026-05-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_transaction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage used', max_digits=5),
        ),
    ]
