# Generated by Django 5.2.5 on 2026-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallettransaction_transaction_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_account_number',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(default=434353544, help_text='Bank Account or Mobile Number', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_uuid',
            field=models.CharField(blank=True, help_text='PayChangu Bank UUID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='payout_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='mobile_money', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
