# Generated by Django 5.2.5 on 2026-08-23 08:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_remove_withdrawal_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywallet',
            name='total_processing_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative processing fees paid to payment gateways', max_digits=12),
        ),
    ]
