# Generated by Django 5.2.5 on 2026-08-23 08:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_companywallet_total_processing_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companywallet',
            name='total_processing_fees',
        ),
        migrations.AddField(
            model_name='companywallet',
            name='total_gateway_fees_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payout processing fees charged by PayChangu', max_digits=12),
        ),
        migrations.AddField(
            model_name='companywallet',
            name='vault_processing_buffer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reserved pool to cover PayChangu payout transaction fees', max_digits=12),
        ),
        migrations.AlterField(
            model_name='companywallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net company profit available after reserving payout fees', max_digits=12),
        ),
        migrations.AlterField(
            model_name='companywallet',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross commission earnings collected across all sales', max_digits=12),
        ),
    ]
