# Generated by Django 5.2.5 on 2026-09-22 15:50

import career.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(choices=[('Lilongwe', 'Lilongwe'), ('Blantyre', 'Blantyre'), ('Mzuzu', 'Mzuzu'), ('Zomba', 'Zomba'), ('Mangochi', 'Mangochi'), ('Other', 'Other')], max_length=50)),
                ('position', models.CharField(default='MalaTrade Marketing Ambassador', max_length=100)),
                ('cv_file', models.FileField(upload_to=career.models.cv_upload_path)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('opt_in_future_vacancies', models.BooleanField(default=False, verbose_name='Notify me about future job vacancies at MalaTrade')),
                ('opt_in_announcements_products', models.BooleanField(default=False, verbose_name='Receive news, announcements, and featured products from MalaTrade')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
