# Generated by Django 5.2.5 on 2026-09-22 16:06

import career.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=career.models.cv_upload_path),
        ),
    ]
