# Generated by Django 5.2.5 on 2026-09-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_jobapplication_cv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='URL friendly identifier (e.g., marketing-ambassador)', unique=True)),
                ('description', models.TextField(help_text='Role details and duties')),
                ('responsibilities', models.TextField(blank=True, help_text='Enter key responsibilities')),
                ('qualifications', models.TextField(blank=True, help_text='Enter key requirements/qualifications')),
                ('locations', models.CharField(default='Lilongwe, Blantyre, Mzuzu, Zomba, Mangochi', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Check to keep position open')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='position',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='career.vacancy'),
        ),
    ]
