# Generated by Django 5.2.5 on 2026-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_e', models.CharField(choices=[('product', 'Product'), ('shop', 'Shop'), ('event', 'Event'), ('lodge', 'Lodge'), ('property', 'Property')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('weight', models.FloatField(default=1.0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
