# Generated by Django 5.2.5 on 2026-06-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={'ordering': ['-score', '-created_at']},
        ),
        migrations.RenameField(
            model_name='feeditem',
            old_name='weight',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='feeditem',
            old_name='type_e',
            new_name='type',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
