# Generated by Django 6.0.4 on 2026-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_phone_number',
            field=models.TextField(blank=True, max_length='100', null=True),
        ),
    ]
