# Generated by Django 6.0.4 on 2026-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Groceries', 'Groceries'), ('Home', 'Home'), ('Beauty', 'Beauty')], default='Electronics', max_length=50),
        ),
    ]
