# Generated by Django 6.0.4 on 2026-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(default='Learn more', max_length=50),
        ),
    ]
