# Generated by Django 6.0.4 on 2026-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appversion',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appversion',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
