# Generated by Django 5.2.5 on 2026-06-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cj_variant_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size_eu', models.IntegerField(blank=True, null=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_g', models.IntegerField(default=0, help_text='Weight in grams to evaluate future shipping fees')),
                ('stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_variants', to='products.product')),
            ],
        ),
    ]
