# Generated by Django 5.2.5 on 2026-06-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_shoevariant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoeVariant',
            new_name='ProductVariant',
        ),
    ]
