# Generated by Django 5.2.5 on 2026-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aliexpress_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
