# Generated by Django 5.2.5 on 2026-07-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_aliexpress_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(default='Shoes', max_length=50),
        ),
    ]
