# Generated by Django 5.2.5 on 2026-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_brand_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_duration',
            field=models.CharField(blank=True, default='2-4 business days', help_text='Estimated time for delivery (e.g., 24 hours, 3-5 days)', max_length=100),
        ),
    ]
